// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr6fbo4Hhagjgaa2lZO19Xgtf2I2u2o_k',
    appId: '1:186143774309:web:5c907068b94bfdf0f3188c',
    messagingSenderId: '186143774309',
    projectId: 'my-spotify-clone-project',
    authDomain: 'my-spotify-clone-project.firebaseapp.com',
    storageBucket: 'my-spotify-clone-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCy3l5HYVOLQA336Gw-6dxi0n_oFvd42Y',
    appId: '1:186143774309:android:2a8c34e339e57b13f3188c',
    messagingSenderId: '186143774309',
    projectId: 'my-spotify-clone-project',
    storageBucket: 'my-spotify-clone-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3mlwyS5IMlUuMI5pyOu1CLknEe5d1oIs',
    appId: '1:186143774309:ios:5a312bf620971cb5f3188c',
    messagingSenderId: '186143774309',
    projectId: 'my-spotify-clone-project',
    storageBucket: 'my-spotify-clone-project.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3mlwyS5IMlUuMI5pyOu1CLknEe5d1oIs',
    appId: '1:186143774309:ios:5a312bf620971cb5f3188c',
    messagingSenderId: '186143774309',
    projectId: 'my-spotify-clone-project',
    storageBucket: 'my-spotify-clone-project.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr6fbo4Hhagjgaa2lZO19Xgtf2I2u2o_k',
    appId: '1:186143774309:web:bf6e13629f0630ecf3188c',
    messagingSenderId: '186143774309',
    projectId: 'my-spotify-clone-project',
    authDomain: 'my-spotify-clone-project.firebaseapp.com',
    storageBucket: 'my-spotify-clone-project.appspot.com',
  );
}